### ISSUE TITLE
Migrate to Confirmation Dialog instead of Menu

### ISSUE THREAD

**Issue by kdjohnson** [Aaron-G-9/reactjs-calendar#42]

**Comment by amgoodfellow** [comment]
##### A little explanation for this:

I don't really like the confirmation dialog instead of the menu, but as things currently stand, when a popover menu is put into uPortal (which will hopefully be a big user of this project), it floats over content when scrolling. It doesn't stay anchored to it's element correctly. Hopefully this will be fixed as the Material-UI v1 becomes more mature. Until that time, we'll switch to a confirmation dialog which is functionally similar, if a little bit un-intuitive.
